# parameters

const anteBonusD = (
    prial=5,
    straightflush=4,
    straight=1
)

# Constants calculated

const PRIAL_HAND_COMBOS = 4 * 3 * 2 ÷ 3 ÷ 2
const PRIAL_COMBOS = PRIAL_HAND_COMBOS * 13

const STRAIGHT_FLUSH_HAND_COMBOS = 4
const STRAIGHT_FLUSH_COMBOS = STRAIGHT_FLUSH_HAND_COMBOS * 12

const STRAIGHT_HAND_COMBOS = 4 * 4 * 4 - STRAIGHT_FLUSH_HAND_COMBOS
const STRAIGHT_COMBOS = STRAIGHT_HAND_COMBOS * 12

const FLUSH_HAND_COMBOS = 4
const FLUSH_COMBOS = FLUSH_HAND_COMBOS * 13 * 12 * 11 ÷ 3 ÷ 2 - STRAIGHT_FLUSH_COMBOS

const PAIR_HAND_COMBOS = 4 * 4 * 3 ÷ 2
const PAIR_COMBOS = PAIR_HAND_COMBOS * 13 * 12

const HIGH_CARD_HAND_COMBOS = 4 * 4 * 4 - FLUSH_HAND_COMBOS
const HIGH_CARD_COMBOS = HIGH_CARD_HAND_COMBOS * 13 * 12 * 11 ÷ 3 ÷ 2 - STRAIGHT_COMBOS

const TOTAL_COMBOS = 52 * 51 * 50 ÷ 3 ÷ 2

const NQ_COMBOS = (10 * 9 * 8 ÷ 3 ÷ 2 - 8) * (4 * 4 * 4 - 4)

const J_PRIAL_COMBOS = PRIAL_HAND_COMBOS * 10
const J_STRAIGHT_FLUSH_COMBOS = STRAIGHT_FLUSH_HAND_COMBOS * 12
const J_STRAIGHT_COMBOS = STRAIGHT_HAND_COMBOS * 8
const J_FLUSH_COMBOS = FLUSH_HAND_COMBOS * 10 * 9 * 8 ÷ 3 ÷ 2 - STRAIGHT_FLUSH_COMBOS

const J_TOTAL_COMBOS = 40 * 39 * 38 ÷ 3 ÷ 2


const COMBO_TYPES = (0,HIGH_CARD_COMBOS,PAIR_COMBOS,FLUSH_COMBOS,STRAIGHT_COMBOS,STRAIGHT_FLUSH_COMBOS,PRIAL_COMBOS)

